---
- hosts: all
  user: root

  tasks:
    - name: "Add nginx PPA repository"
      apt_repository: repo="ppa:nginx/stable"

    - name: "Install nginx"
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - nginx
