---
- name: "Install postgres and dependencies"
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql
    - python-psycopg2
    - postgresql-contrib
    - postgresql-server-dev-9.3

- name: "Create a db user"
  postgresql_user: name={{user_name}} password={{ item }} role_attr_flags=SUPERUSER
  with_password: credentials/{{user_name}}_password.pass
  become: yes
  become_user: postgres

- name: "Create a database"
  postgresql_db: name={{database_name}} owner={{user_name}} encoding=UTF8 template=template0
  become: yes
  become_user: postgres
